### ISSUE TITLE
Question: Braintree + how to work with additional .js files

### ISSUE THREAD

**Issue by simonhrogers** [wearelucid/nuxt-netlify-functions-example#6]
I am trying to create a Braintree integration ... but I am not sure on the setup for additional files – any help appreciated. 

If I define the following in `gateway.js`: 

```
import { connect, Environment } from 'braintree';
require('dotenv').config();

const {
  BT_ENVIRONMENT,
  BT_MERCHANT_ID,
  BT_PUBLIC_KEY,
  BT_PRIVATE_KEY
} = process.env;

const environment =
  BT_ENVIRONMENT.charAt(0).toUpperCase() + BT_ENVIRONMENT.slice(1);

const gateway = connect({
  environment: Environment[environment],
  merchantId: BT_MERCHANT_ID,
  publicKey: BT_PUBLIC_KEY,
  privateKey: BT_PRIVATE_KEY
});

export default gateway;
```

How do I include this in my function `braintree-get-token.js`?

```
import gateway from '/gateway.js';

export async function handler(event, context) {

  const response = await gateway.clientToken.generate();

  const clientToken = response.clientToken;

  return {
    statusCode: 200,
    body: JSON.stringify({ token: clientToken })
  };
}
```

Currently this results in an error:

`TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object`

https://github.com/simonhrogers/nuxt-netlify-functions-example

Many thanks, sorry for the silly question – this would be a really helpful addition to the repo

**Comment by mornir** [comment]
Hi!
I think you made a typo in your relative import: from "/gateway.js"
And if you're not using a build step, I would use CommonJS instead of ESM modules.
